name = "DynamicTimeseries"
uuid = "1899e1d9-0e62-5b08-93e8-96938e3582a6"
authors = ["Galen Lynch <galen.lynch@gmail.com>"]
version = "0.1.5"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
SignalIndices = "18f53e89-494d-4131-905c-653e8ada6cd8"
SortedIntervals = "b6c59e15-8662-4f8a-b157-cd910e143dcd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
EventIntervals = "1751c77c-d90c-5130-9faa-3b4ea8d90a70"
Statistics =  "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DSP = "0.5 - 0.8"
FFTW = "0.2.4 - 1"
SignalIndices = "0.1"
SortedIntervals = "0.1"
EventIntervals = "0.1.5"
julia = "1.6"
