name = "GLTimeseries"
uuid = "1899e1d9-0e62-5b08-93e8-96938e3582a6"
authors = ["Galen Lynch <galen.lynch@gmail.com>"]
version = "0.1.3"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GLUtilities = "8b4c6747-1f02-570a-a961-a96037df41d6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
PointProcesses = "1751c77c-d90c-5130-9faa-3b4ea8d90a70"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics =  "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Compat = "1 - 3"
DSP = "0.5 - 0.6"
FFTW = "0.2.4 - 1"
GLUtilities = "0.0.5 - 0.2"
Missings = "0.2 - 0.4"
PointProcesses = "0.0.2 - 0.1"
julia = "0.7 - 1"
